branch-defaults:
  master:
    environment: golangApp-env
global:
  application_name: golang-app
  default_ec2_keyname: test
  default_platform: 64bit Amazon Linux 2016.03 v2.1.6 running Go 1.5
  default_region: us-west-2
  profile: eb-cli
  sc: git
